# Generated by Django 3.2.3 on 2021-05-26 08:48

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KampeerSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('info_text', models.CharField(max_length=200)),
                ('camp_date', models.DateTimeField(verbose_name='Kampeerdatum')),
            ],
        ),
    ]
